### PR TITLE
fix(types): named and default exports and types in MJS 

### LINKED ISSUE #24: Typescript import example
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have been unable to import this module in Typescript. Can you provide an example?

This:

```Typescript
import FastifyOtelInstrumentation from '@fastify/otel'
export const fastifyOtel = new FastifyOtelInstrumentation({
  servername: 'my-app',
  registerOnInitialization: true,
})
```

Yields:

```
This expression is not constructable.
  Type 'typeof import("/Users/me/git/my-app/node_modules/@fastify/otel/index")' has no construct signatures.ts(2351)
```

And this:
```Typescript
import { FastifyOtelInstrumentation } from '@fastify/otel'
export const fastifyOtel = new FastifyOtelInstrumentation({
  servername: 'my-app',
  registerOnInitialization: true,
})
```

Yields:

```
import { FastifyOtelInstrumentation } from '@fastify/otel'
         ^

SyntaxError: The requested module '@fastify/otel' does not provide an export named 'FastifyOtelInstrumentation'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

### PR DESCRIPTION
**Pull request by bcomnes**
Here is a second attempt at https://github.com/fastify/otel/pull/30. This does a few things:

- Fix default and named exports in mjs consumers by assigning module.exports and module.exports.FastifyOtelInstrumentation instead of adding static properties to the class. The properties show up as `module.exports` in mjs and named exports were not working before. Now they are importable in cjs and mjs as one would expect.
- Added tests for mjs imports. 
- Convert index.d.ts to use `export = ` because this is a type file for a cjs module so we cannot use `export foo` or `export default` anywhere without introducing a mismatch between the module system being used in the implementation and types.
- Move the pure types into a type.d.ts file, where we can use named exports, since exporting them out of a cjs type file is very weird and awkward and requires typeof use by consumers. 
- Moved the fastify mocks from https://github.com/fastify/otel/issues/32
 to a fastify-mocks.d.ts file to also use named exports but to also discourage their import from consumers, just in case their editor tries to import a fastify type incorrectly out of this module. In general mocking these types seems like it's asking for trouble from a maintenance perspective. Fastify was previously an unlisted peer dependency (presumably because listed peer dependencies can be a nightmare) just as it is in nearly every other fastify plugin. Mocking these types will require ongoing one-off maintenance and will also potentially mask breaking issues as they materialize. Maybe someone more familiar with the deliberate strategy of using unlisted peer dependencies can chime in. 

Fixes: https://github.com/fastify/otel/issues/24

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -48,8 +48,6 @@ const kAddHookOriginal = Symbol('fastify otel addhook original')
 const kSetNotFoundOriginal = Symbol('fastify otel setnotfound original')
 
 class FastifyOtelInstrumentation extends InstrumentationBase {
-  static FastifyOtelInstrumentation = FastifyOtelInstrumentation
-  static default = FastifyOtelInstrumentation
```
Comment (bcomnes) [inline index.js:52]: Simulating a default export in cjs only works in bundlers. This is node.js code so we need to assign to module.exports.

**Comment by bcomnes** [comment]
Actually, I don't know why I opened a second PR. Lets just use the old one.

**Comment by bcomnes** [comment]
I made a new one because I can't re-open it. Arg. Sorry for the noise.

**Comment by bcomnes** [comment]
cc previous participants: @Eomm @mcollina @voxpelli @metcoder95

File: test/api.test.mjs
Comment (metcoder95) [inline test/api.test.mjs:1]: Can you add the other tests that lives within `api.test.js`?

File: fastify-mocks.d.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
+// fastify-mocks.d.ts
+
+// These types were mocked due to a desire to not utilize fastify as an unlisted peer dependency.
+// https://github.com/fastify/otel/issues/32
```
Comment (mcollina) [inline fastify-mocks.d.ts:4]: I generically don't see those as needed. We don't use them anywhere else in our organization.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: fastify-mocks.d.ts (hunk 2 above)
Comment (bcomnes) [reply fastify-mocks.d.ts:4]: Just to clarify, these are already in this codebase. Do you want me to remove them in this PR and suggest downstream install fastify as a devDependency as well?

File: test/api.test.mjs
Comment (bcomnes) [reply test/api.test.mjs:1]: Can you clarify? Test the named and default export in `api.test.js` as well?

Comment (metcoder95) [reply test/api.test.mjs:1]: I'm referring to this one: https://github.com/fastify/otel/blob/db52f0ea5fbbfa00aaa13d355f93534588633192/test/api.test.js#L29-L40

Comment (metcoder95) [reply test/api.test.mjs:1]: just for the sake of completeness

File: fastify-mocks.d.ts (hunk 2 above)
Comment (metcoder95) [reply fastify-mocks.d.ts:4]: This was added as part of #32 to avoid TS conflicts with unlisted dependencies.

Don't have a strong opinion while keeping it or not, it makes the code more complex as we are doing mimic of Fastify types and we most likely will need to update them on new major if something changes.

Happy to go either way.

**Review by mcollina — APPROVED** [review]
lgtm

File: fastify-mocks.d.ts (hunk 2 above)
Comment (mcollina) [reply fastify-mocks.d.ts:4]: I think they should go away. If we need to play ball with Sentry, let's try adding the peerDependency and see how many problems we are going to get.

**Review by gurgunday — APPROVED** [review]

File: fastify-mocks.d.ts (hunk 2 above)
Comment (bcomnes) [reply fastify-mocks.d.ts:4]: @metcoder95 want me to do that in this PR? Or someone want to do it in a separate PR?

**Comment by mcollina** [comment]
@bcomnes could you address the last comment from @metcoder95 ?

**Comment by bcomnes** [comment]
As soon as I find a moment this weekend.

**Comment by bcomnes** [comment]
Ok @mcollina and @metcoder95, I think this is fixed up now.

**Comment by bcomnes** [comment]
I fixed the lint. I think the eslint rule was applying .ts rules to a .d.ts file so I disabled that one one line. LMK if you have a another preferred solution!

**Comment by bcomnes** [comment]
Checks are green, just need one more review after the push.

File: index.d.ts [hunk 3]
```diff
@@ -1,34 +1,34 @@
...
 
 declare module 'fastify' {
   interface FastifyRequest {
     opentelemetry(): FastifyOtelRequestContext
   }
 }
 
-declare class FastifyOtelInstrumentation<Config extends FastifyOtelInstrumentationOpts = FastifyOtelInstrumentationOpts> extends InstrumentationBase<Config> {
-  static FastifyInstrumentation: FastifyOtelInstrumentation
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (gurgunday) [inline index.d.ts:18]: What is not being used? Sorry if I missed this, it seems new?

Comment (bcomnes) [reply index.d.ts:18]: I think because it's a .d.ts file but tbh I'm not sure. Open to suggestion.

**Comment by bcomnes** [comment]
I think we're all good here?

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by gurgunday — APPROVED** [review]
